import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const montserrat = Montserrat({
  variable: "--montserrat",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`bg-gradient font-montserrat grid grid-cols-(--body-cols) grid-rows-(--body-rows) text-(--foreground)`}
      >
        <Header />

        {children}
      </body>
    </html>
  );
}
